server:
  port: 8000

spring:
  config:
    import: application-secret.yml
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-management-users
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/api/user-management/users/**
          filters:
            - RewritePath=/api/user-management/users/(?<segment>.*), /api/users/$\{segment}

        - id: user-management-auth
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/api/user-management/auth/**
          filters:
            - RewritePath=/api/user-management/auth/(?<segment>.*), /auth/$\{segment}

        - id: blog-service
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/api/blog-service/**
          filters:
            - RewritePath=/api/blog-service/(?<segment>.*), /$\{segment}

      globalcors:  # 이 들여쓰기로 수정
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
